# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.x'
          channel: 'stable'
          
      - name: enable flutter desktop support
        run: flutter config --enable-windows-desktop

      - name: build flutter app
        run: flutter build windows
        
      - name: upload app (internal)
        uses: actions/upload-artifact@v2
        with:
          name: flutter_textfield_test
          path: build\windows\runner\Release
          retention-days: 1
